apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: | # overriding the default configMap as it requires a postgresql, we could use sqlite instead though
    app:
      title: Backstage Platform Insights
      baseUrl: http://localhost:7007
    backend:
      baseUrl: http://localhost:7007
      listen:
        host: 0.0.0.0
        port: 7007
      cors:
        origin: http://localhost:7007
        methods: [GET, HEAD, PUT, POST, DELETE, PATCH]
        credentials: true
      # DEV ONLY, used to bypass authentication error 
      auth:
        dangerouslyDisableDefaultAuthPolicy: true
